version: '3.8'
networks:
  proxy:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
  data-science:
    image: tensorflow/tensorflow:latest-gpu-jupyter
    ports:
      - ${tensorflow_port}:8888
    volumes:
      - ./tensorflow:/tf/notebooks
    environment:
    - JUPYTER_TOKEN=${pw}
    - JUPYTER_ENABLE_LAB=yes
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # command: bash -c "source /etc/bash.bashrc && \
    #   apt update && apt upgrade -y && \
    #   apt install golang-go -y & \
    #   python -m pip install --user --upgrade pip & \
    #   wait && \
    #   jupyter notebook --notebook-dir=/tf --ip 0.0.0.0 --no-browser --allow-root"